---
- block:
    - name: apt update && upgrade
      apt:
        cache_valid_time: 3600
        upgrade: safe
    - name: create kalkspace settings dir
      file:
        path: /etc/kalkspace
        state: directory
        owner: mete-mgmt
        group: mete-mgmt
    - name: install docker
      apt:
        pkg:
          - docker.io
          - docker-compose
          - python3-docker
    - name: ensure mete-mgmt can run docker
      user:
        name: mete-mgmt
        groups: docker
        append: yes
    - name: enable docker
      systemd:
        name: docker
        enabled: yes
        masked: no
        state: started
    - name: mete directory
      file:
        path: /etc/kalkspace/mete
        state: directory
        owner: mete-mgmt
        group: mete-mgmt
    - name: copy docker-compose definition
      copy:
        src: files/docker-compose.yml
        dest: /etc/kalkspace/mete/docker-compose.yml
        owner: mete-mgmt
        group: mete-mgmt
    - name: start mete setup
      community.general.docker_compose:
        project_src: /etc/kalkspace/mete/
        pull: yes

  become: true
  become_user: root
