---
- block:
    - name: apt update && upgrade
      apt:
        cache_valid_time: 3600
        upgrade: safe
    - name: install tablet kiosk required packages
      apt:
        pkg:
          - firefox-esr
          - phoc
          - foot
          - curl
    - name: remove pulseaudio
      apt:
        name: pulseaudio
        state: absent
    - name: copy getränkekiosk
      copy:
        src: files/getraenke-kiosk.service
        dest: /etc/systemd/system/getraenke-kiosk.service
        owner: getraenkekasse-mgmt
        group: getraenkekasse-mgmt
        mode: 0755
      notify:
        - restart getränkekiosk
    - name: create kalkspace settings dir
      file:
        path: /etc/kalkspace
        state: directory
        owner: getraenkekasse-mgmt
        group: getraenkekasse-mgmt
    - name: copy phoc.ini
      copy:
        src: files/phoc.ini
        dest: /etc/kalkspace/phoc.ini
      notify:
        - restart getränkekiosk
    - name: copy kiosk.sh
      template:
        src: templates/kiosk.sh.j2
        dest: /etc/kalkspace/kiosk.sh
        owner: getraenkekasse-mgmt
        group: getraenkekasse-mgmt
        mode: 0755
      notify:
        - restart getränkekiosk
    - name: enable getränkekiosk
      systemd:
        name: getraenke-kiosk
        enabled: yes
        daemon_reload: yes
        state: started
    - name: reduce stop timeout because containerd-shim hangs
      ansible.builtin.lineinfile:
        path: /etc/systemd/system.conf
        regexp: "^DefaultTimeoutStopSec="
        line: DefaultTimeoutStopSec=5s

  become: true
  become_user: root
