---
- block:
    - name: Set hostname
      ansible.builtin.hostname:
        name: getraenkekasse
    - name: apt update && upgrade
      apt:
        cache_valid_time: 3600
        upgrade: safe
    - name: install tablet kiosk required packages
      apt:
        pkg:
          # firefox slow af but supports virtual keyboard
          - firefox
          - phoc
          - foot
          - lm-sensors
          - mesa-utils
          - xdg-utils
          - squeekboard
          - fonts-noto-cjk
          - fonts-noto-cjk-extra
          - fonts-noto-color-emoji
          - adwaita-icon-theme-full
          - gnome-icon-theme
    - name: ensure getraenkekasse is in video and audio group
      user:
        name: getraenkekasse
        groups:
          - audio
          - render
          - video
        append: yes
    # read only for user
    - name: create bash_profile
      copy:
        src: files/bash_profile
        dest: /home/getraenkekasse/.bash_profile
        owner: root
        group: root
        mode: 0755
    - name: get getraenkekasse uid
      getent:
        database: passwd
        key: getraenkekasse
    - name: create kalkspace settings dir
      file:
        path: /etc/kalkspace
        state: directory
        owner: root
        group: root
    - name: copy phoc.ini
      copy:
        src: files/phoc.ini
        dest: /etc/kalkspace/phoc.ini
      notify:
        - restart getränkekiosk
    - name: copy kiosk.sh
      template:
        src: templates/kiosk.sh.j2
        dest: /etc/kalkspace/kiosk.sh
        owner: root
        group: root
        mode: 0755
      notify:
        - restart getränkekiosk
    - name: create systemd getty override dir
      file:
        path: /etc/systemd/system/getty@tty1.service.d/
        state: directory
        owner: root
        group: root
    - name: autologin getraenkekasse
      copy:
        src: files/autologin.conf
        dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
        owner: root
        group: root
        mode: 0755
      notify:
        - restart getränkekiosk
    - name: enable squeekboard
      ansible.builtin.shell: gsettings set org.gnome.desktop.a11y.applications screen-keyboard-enabled true
      become_user: getraenkekasse
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd.getraenkekasse[1] }}"
      notify:
        - restart getränkekiosk
    - name: set keyboard layout
      ansible.builtin.shell: gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'de')]"
      become_user: getraenkekasse
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd.getraenkekasse[1] }}"
      notify:
        - restart getränkekiosk

  become: true
  become_user: root
