---
- block:
    - name: apt update && upgrade
      apt:
        cache_valid_time: 3600
        upgrade: safe
    - name: install tablet kiosk required packages
      apt:
        pkg:
          - chromium
          - curl
          - lightdm
          - xorg
    - name: remove pulseaudio
      apt:
        name: pulseaudio
        state: absent
    - name: copy getränkekiosk
      copy:
        src: .xinitrc
        dest: /home/getraenkekasse/.xinitrc
        owner: getraenkekasse
        group: getraenkekasse
        mode: 0755
      notify:
        - restart getränkekiosk
    - name: link the FUCKING X11 UNFUG
      file:
        src: /home/getraenkekasse/.xinitrc
        dest: /home/getraenkekasse/.xsession
        owner: getraenkekasse
        group: getraenkekasse
        state: link
      notify:
        - restart getränkekiosk
    - name: create kalkspace settings dir
      file:
        path: /etc/kalkspace
        state: directory
        owner: getraenkekasse-mgmt
        group: getraenkekasse-mgmt
    - name: copy kiosk.sh
      template:
        src: templates/kiosk.sh.j2
        dest: /etc/kalkspace/kiosk.sh
        owner: getraenkekasse-mgmt
        group: getraenkekasse-mgmt
        mode: 0755
      notify:
        - restart getränkekiosk
    - name: enable getränkekiosk
      systemd:
        name: getraenke-kiosk
        enabled: yes
        daemon_reload: yes
        state: started
    - name: reduce stop timeout because containerd-shim hangs
      ansible.builtin.lineinfile:
        path: /etc/systemd/system.conf
        regexp: "^DefaultTimeoutStopSec="
        line: DefaultTimeoutStopSec=5s
    - name: autologin as kasse
      ansible.builtin.lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: "^autologin-user="
        insertafter: "#autologin-user="
        line: autologin-user=getraenkekasse
    - name: enable lightdm
      systemd:
        name: lightdm
        enabled: yes
        daemon_reload: yes
        state: started

  become: true
  become_user: root
