---
- block:
    - name: add non-free repo
      apt_repository:
        repo: "deb http://mirror.netcologne.de/debian/ bullseye non-free"
        state: present
        filename: bullseye non-free
        update_cache: yes
    - name: apt update && upgrade
      apt:
        cache_valid_time: 3600
        upgrade: safe
    - name: install firmware
      apt:
        pkg:
          - firmware-intel-sound
          - firmware-atheros

  become: true
  become_user: root
