---
- name: restart traefik
  community.general.docker_compose:
    project_src: /etc/kalkspace/getraenkekasse/
    pull: yes
    restarted: yes
    services:
      - traefik
- name: reload systemd
  systemd:
    daemon_reload: yes
  become: true
