---
- block:
    - name: apt update && upgrade
      apt:
        cache_valid_time: 3600
        upgrade: safe
    - name: create kalkspace settings dir
      file:
        path: /etc/kalkspace
        state: directory
        owner: root
        group: root
    - name: install required packages
      apt:
        pkg:
          - curl
          - docker.io
          - docker-compose
          - python3-docker
          - pcscd
          - libacsccid1
          - prometheus-node-exporter
    - name: copy stornoschluessel udev rules
      copy:
        src: files/52-storno.rules
        dest: /etc/udev/rules.d/52-storno.rules
    - name: enable docker
      systemd:
        name: docker
        enabled: yes
        masked: no
        state: started
    - name: enable pcscd
      systemd:
        name: pcscd
        enabled: yes
        masked: no
        state: started
    - name: getraenkekasse directory
      file:
        path: /etc/kalkspace/getraenkekasse
        state: directory
        owner: root
        group: root
    - name: copy docker-compose definition
      copy:
        src: files/docker-compose.yml
        dest: /etc/kalkspace/getraenkekasse/docker-compose.yml
        owner: root
        group: root
    - name: create traefik.toml
      ansible.builtin.template:
        src: templates/traefik.toml.j2
        dest: /etc/kalkspace/getraenkekasse/traefik.toml
        owner: root
        group: root
        mode: 0755
      notify:
        - restart traefik
    - name: create fileprovider.toml
      ansible.builtin.template:
        src: templates/fileprovider.toml.j2
        dest: /etc/kalkspace/getraenkekasse/fileprovider.toml
        owner: root
        group: root
        mode: 0755
    - name: copy getraenkekasse-online
      template:
        src: templates/getraenkekasse-online.sh.j2
        dest: /etc/kalkspace/getraenkekasse/getraenkekasse-online.sh
        owner: root
        group: root
        mode: 0755
    - name: copy getraenkekasse-online service
      template:
        src: files/getraenkekasse-online.service
        dest: /etc/systemd/system/getraenkekasse-online.service
        owner: root
        group: root
      notify:
        - reload systemd
    - name: start getraenkekasse setup
      community.general.docker_compose:
        project_src: /etc/kalkspace/getraenkekasse/
        pull: yes
        recreate: smart
      # for development purposes there is "localhost"
      # if we deploy live traefik needs additional host rule so the traefik letsencrypt host magic works
      # ugly but works :S
      environment:
        TRAEFIK_HOST_RULE: "{{ (public_hostname != 'localhost') | ternary('Host(`' + public_hostname + '`) && ', '') }}"

  become: true
  become_user: root
