version: "3"
volumes:
  system:
  database:
services:
  db:
    image: postgres:10-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mete
    volumes:
      - database:/var/lib/postgresql/data
  backend:
    environment:
      RAILS_ENV: production
    image: chaosdorf/mete
    volumes:
      - system:/app/public/system
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "80:80"
