---
- name: Configure kalkspace getränkekassen tablet
  hosts:
    - tablet
  roles:
    - name: user
      tags: user
    - name: getraenkekasse
      tags: getraenkekasse
    - name: kiosk
      tags: kiosk
